### ISSUE TITLE
Remove Statue

### ISSUE THREAD

**Issue by Kami-Interface** [Team-QUIET/QUIET-Community-Edition#107]

**Comment by PurpleMossClump** [comment]
Even after it was fixed, it's just not a very good unit. It's supposed to be a hit-and-run, flanking raider tank, but it's not very good at that. Poor damage, poor HP, the rockets arc up way too high. 

I would say we try to fix it, but even if it were fixed, it would be wrestling with the Pillar as another T2 tank.

**Comment by Kami-Interface** [comment]
I don't think it would be possible to keep the two far enough apart. You'd essentially have one tank with lower movement speed, less HP and less dmg, less cost, and another tank with more of those things, while neither of them is the T2.5 unit

**Comment by Azraeel** [comment]
@PurpleMossClump @Kami-Interface since PMC fixed the rockets have a rediscussion on this please

**Comment by PurpleMossClump** [comment]
I think after having the Pillar having its speed reduced, HP increased, DPS fixed, now a proper Heavy Tank and with the Mongoose nerfs, the Statue stands out a little more as a Light Tank. It's by no means flashy, but for what its worth I've seen M28 build it. 

I think it's worth keeping for now and we can reopen the discussion if necessary.
