### ISSUE TITLE
Remove SSD Hope

### ISSUE THREAD

**Issue by Kami-Interface** [Team-QUIET/QUIET-Community-Edition#118]

**Comment by PurpleMossClump** [comment]
Why?

**Comment by Kami-Interface** [comment]
Squareshield is a bad implementation to begin with. The plan is that all factions will lose their squareshield

**Comment by PurpleMossClump** [comment]
I don't disagree. Squareshields are pretty 'extra'.

**Comment by PurpleMossClump** [comment]
I'll expand upon my reasons.
Squareshields feel, imo, inorganic to the design of the game; They feel very tacked-on, as if they were tailored for a particular template design, and not something with an organic place within each faction. I can't even decide which faction _would_ have one, if any one faction was to keep it, as it just feels so strange as an addition.

**Comment by Kami-Interface** [comment]
I think the other shields are a lot more interesting (artillery shield, pillar of prominence for example)
Also, I've never seen anyone of us ever build it. I don't think it will be missed

**Comment by PurpleMossClump** [comment]
Yeah, each faction also already has their own take on a Heavy shield. 
UEF has the Arty shield and the big T4 dome
Cybran has the Iron Curtain
Aeon has the PoP
Seraphim has their drone bubble party.

Squareshields just feel too identical across the factions. They're practically just reskins of each other.
