### ISSUE TITLE
Increase LOD value on natural reclaim

### ISSUE THREAD

**Issue by Kami-Interface** [Team-QUIET/QUIET-Community-Edition#142]
Up the LOD on natural reclaim which gives mass, mainly the small stones

**Comment by PurpleMossClump** [comment]
Is that handled by the game, or does that need to be done at the Map Editor?

**Comment by Kami-Interface** [comment]
It needs to be changed on all blueprints on all objects, OR, changed by the initialisation script so it's adjusted when game starts. I wrote the code for it already but need to test it a bit more

**Comment by Azraeel** [comment]
Done!
