### ISSUE TITLE
[Short Term] Nerf T2.5 & T3.5 Speed

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#148]

**Comment by Azraeel** [comment]
is everyone on board with this continuation of the T1.5 Speed stuff 

@Kami-Interface @rajderks @PurpleMossClump @loudpatches

**Comment by Kami-Interface** [comment]
How come we're nerfing the speed of T2.5 and T3.5 units? I thought the original issue was T1.5 (and in some sense all T1 units) were too fast

**Comment by PurpleMossClump** [comment]
I don't mean to over-expand the scope of an issue, however the way I see it, we should take a step back and look at T1, T2, T3 and T4 scaling and how they balance with each other in broad terms. 

We should define expectations out of each Tier and how they should scale with each other. If we take care of the foundational expectations now, we can make balance decisions down the line much simpler by laying out the expectations of cost and performance for a given unit in a given tier, leaving some play for factional diversity and specializations.
