### ISSUE TITLE
[Long Term] Introduce DamageRadius for LOUD Units (That should have it)

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#168]
This will require in-depth discussion on units, I introduced throughout LOUD most units even experimental lack large or even medium sized DamageRadius on their weapons. 

This is most likely due to the direction of LOUD in nullifying and reducing DamageRadius in the game overrall.

**Comment by Goldymires** [comment]
Is that AoE gonna be based on the visual? Like..should the AoE match the visual?
