### ISSUE TITLE
Nerf SACUs 

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#17]

**Comment by loudpatches** [comment]
is cybran sacu stun vanilla behavior?

**Comment by Azraeel** [comment]
No

**Comment by Azraeel** [comment]
I was more so talking about nerfing the spam of SACUs you see late game lol

**Comment by loudpatches** [comment]
I was reminded of the 32K shield uef damage magnets, the cybran stun lockers, the seraphim non-targetables, etc.

**Comment by Azraeel** [comment]
Well more excuses to nerf them in retrospect

**Comment by Azraeel** [comment]
The shields all come back to damage not being shared meaning Shield Stacking is meta if no shield piercing units are involved.

**Comment by PurpleMossClump** [comment]
Do we want to reduce their max HP as well? Make them a little less tanky?
