### ISSUE TITLE
[Long Term] Fix Shield Skins Not Absorbing AOE

### ISSUE THREAD

**Issue by loudpatches** [Team-QUIET/QUIET-Community-Edition#186]
Looked liked eliash was getting chewed up by dervishes bypassing its skin shield.  maybe rockets....

**Comment by Azraeel** [comment]
Looks like a tougher fix then i thought lots of code to go through probably by next week we'll see. I won't really be working on the weekdays anymore as I need to fix my sleep schedule lol

**Comment by rajderks** [comment]
Point me in the right direction, i can have a look

**Comment by Azraeel** [comment]
@rajderks its a complex piece of work.
it requires integrating additional work from FAF for overspill to fix it.

**Comment by Goldymires** [comment]
There is a script in the titan (T3 UEF Bot) that makes the HP under the skin shield immune when the skin shield is up. Copy that script and paste it over to remove the AoE Bleed through.

**Comment by Azraeel** [comment]
This was fixed just didnt close my bad.
