### ISSUE TITLE
[Short term] Aeon T2 Artillery

### ISSUE THREAD

**Issue by rajderks** [Team-QUIET/QUIET-Community-Edition#190]
The plasma batteries projectiles explode in mid air;
The miasma overshoots (can't reproduce for the life of me)

https://discord.com/channels/1280278037434204203/1280287252379074570/1289220369001091164

**Comment by rajderks** [comment]
I can't fix the miasma.
Git history shows nothing usefull :(

**Comment by loudpatches** [comment]
looking like 
https://github.com/LOUD-Project/Git-LOUD/blob/master/gamedata/lua/lua/sim/defaultweapons.lua#L226  was added, which invokes a function from loudutilities/TrackProj https://github.com/LOUD-Project/Git-LOUD/blob/master/gamedata/lua/lua/loudutilities.lua#L6930

 which has this interesting dispatch....
https://github.com/LOUD-Project/Git-LOUD/blob/master/gamedata/lua/lua/loudutilities.lua#L6944
specifically checks to see if the brain has 'm' in the name.
If I comment out that         proj:ForkThread( Monitor, self)
 from defaultweapons.lua that was added upstream (which only seems to dispatch on m28....) then miasma works.

**Comment by loudpatches** [comment]
We are still seeing bugs with this on certain units.  Trying to reproduce against engineers.
