### ISSUE TITLE
Little Buff Eliash HP Back.

### ISSUE THREAD

**Issue by AmericanSniper** [Team-QUIET/QUIET-Community-Edition#212]
we had a game where 12 dervishes killed eliash and elias so bad, i guess the callibration has begun so let's little pinch it back, till we get the balance Teresas perfectly, i guess ~7k hp buff could give this unit extra time to retreat against that threat.
there is replay in discord on toxic mire, where's eliash and elias sucks against 12 dervishes and 7 sealions. crap to me, crap to others, let's suggest.

**Comment by AmericanSniper** [comment]
also i think bubble shields looks crinji for eliash imo, personal shield much better, and if you think this doesn't work that well due to AoE, I just recommend to move most of hitpoints back to regular HP, when shield is going to have around 25%

**Comment by Azraeel** [comment]
@AmericanSniper Eliash has a personal shield currently, the AoE Bug is fixed.
