### ISSUE TITLE
UEF Thug ui is broken.

### ISSUE THREAD

**Issue by loudpatches** [Team-QUIET/QUIET-Community-Edition#213]
Can't build thug from menu (Icon shows).

**Comment by loudpatches** [comment]
Working in 1.30, broken in 1.32

**Comment by loudpatches** [comment]
bad blueprint merge.  approach of changing buffs to false caused silent problem with bp parse.

**Comment by loudpatches** [comment]
using full blueprint works, but requires bringing in unit.  maybe we need to handle this corner case (removing buffs) with a script.
could envision a custom unit script that removes the buff from the blueprint, or do it in blueprint mod function in blueprints.lua.

Or find compatible values for the buffs merge....
@Azraeel

**Comment by Azraeel** [comment]
Fixed!
