### ISSUE TITLE
Need to add all the unit mods that are require to mod_info

### ISSUE THREAD

**Issue by loudpatches** [Team-QUIET/QUIET-Community-Edition#240]
@Azraeel 
When you stripped out `requires` and `after` to simplify load order with the uid hack, you introduced the hidden problem where if someone disables all mods an tries to turn on quiet, quiet thinks it's fine.  The game will then crash on load because it's trying to hook things or invoke variables that don't exist (implicit dependencies).  We should opt to make dependencies explicit via requires.

Solution is to add them back to the mod_info requires (any of the unit packs we are definitely hooking).  Other implication is that we don't play quiet without these unit packs.

Discovered this trying to debug stuff with vortex.

**Comment by Azraeel** [comment]
Wilco
