### ISSUE TITLE
[Short Term] Cybran Engineer Immunity

### ISSUE THREAD

**Issue by loudpatches** [Team-QUIET/QUIET-Community-Edition#243]
at least 1 case where t1 aeon pd can't hurt them (shooting point blank).
can't reproduce at the moment.

same occurence with t2 field engineer in other game @PurpleMossClump 

Happens with both ai and human controlled engineers.  Uncertain if other faction engineers are impacted.

**Comment by PurpleMossClump** [comment]
It was Cybran T3 Field Engineers and T1 Engineers that I've observed

**Comment by loudpatches** [comment]
addressed in 1f61c464deed89f2efdd671a8c1cc4c22d3c63af
