### ISSUE TITLE
Minor destroyer strategic icon fix

### ISSUE THREAD

**Issue by AmericanSniper** [Team-QUIET/QUIET-Community-Edition#246]
make UEF destroyer icon different with torpedo boat such as,
UES0201 -> StrategicIconName = "icon_ship2_directfire",

make Cybran destroyer strategic icon actually naval icon,
URS0201 -> StrategicIconName = "icon_ship2_antinavy",

**Comment by Azraeel** [comment]
@PurpleMossClump
