### ISSUE TITLE
[Short Term] Fix UEF ACU Firing even when performing actions like Reclaim

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#254]

**Comment by PurpleMossClump** [comment]
The UEF ACU's weapons YawRange was changed to 180, so they can fire in any direction, regardless of where the ACU is facing.

**Comment by Azraeel** [comment]
all commanders have a yawrange of 180

**Comment by PurpleMossClump** [comment]
Well I changed the UEF's Zephyr yawrange to 10 (the value it has in LOUD) and it behaved normally. It wouldn't fire at enemies when reclaiming or building, but would engage normally when idle or told to attack.

**Comment by Azraeel** [comment]
> Well I changed the UEF's Zephyr yawrange to 10 (the value it has in LOUD) and it behaved normally. It wouldn't fire at enemies when reclaiming or building, but would engage normally when idle or told to attack.

Its because it has useing firing solution instead of aimbone, so just remove that instead by setting it to false

**Comment by Azraeel** [comment]
We can probably set that false on all of them
