### ISSUE TITLE
[Medium Term] T2 Seraphim Fighter Bones are rigged incorrectly causing it to miss sometimes

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#255]
Maybe could allow its projectiles to TrackTarget?

**Comment by PurpleMossClump** [comment]
This unit seems to be broken. In sandbox, I've observed that the unit wobbles a lot in pursuits and has a strong tendency to lean backwards, as if the center of gravity is front-loaded. It almost flies as if it is hanging by the front tip and being dragged around.
