### ISSUE TITLE
Megalith Stealth lol

### ISSUE THREAD

**Issue by loudpatches** [Team-QUIET/QUIET-Community-Edition#276]
Should remove the personal stealth that was randomly added.  Let them build operatives as originally intended.

**Comment by AmericanSniper** [comment]
Yeah, he did it in the commit for June 3, 2024, just randomly buffing units. And so often, it's Cybran; I see a pattern. I just can't understand what's in his mind while doing this. 'Oh yo, this ultra-heavy 100k HP unit definitely needs personal stealth. Why shouldn't it be like that, aha! (French accent)
