### ISSUE TITLE
Review all units with Stun or Stealth 

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#5]
The review would see if these units are overpowered due to these abilities or do they even deserve these abilities.

**Comment by Azraeel** [comment]
@loudpatches @Kami-Interface I'm sure if i can add a % chance for the stun to be applied for the Otheeka but if i could i would like too.

Generally, if i removed it the Otheeka would literally be the equal status of the Warhammer, unbuildable.

**Comment by loudpatches** [comment]
@Azraeel 
I think either (loosely sketched)

```lua
function onFire(self)
   if math.random() < 0.9 then
     applyStun()
   end if
  --do other stuff
end
```

or

```lua
local n = math.random(10)
function onFire(self)
   if n < 9 then
     applyStun()
   end if
   n = math.min(n + 1, 1)
  --do other stuff
end
```

I am uncertain of the specific tradeoffs perf wise.  Maybe the PRNG draw is fast enough that it doesn't matter.

I forget how the current stun buffs work; I think they are all guaranteed (maybe the bull is different).

**Comment by Azraeel** [comment]
@Kami-Interface would you be interested in noting all units down that have Stun as well?

**Comment by PurpleMossClump** [comment]
UEF T1 PD Thug
Cybran T1 mobile artillery (this unit has EMP effect in Vanilla SC:FA; Sacrifices damage for stun)

UEF T2 PD Tower Boss
Aeon T2 PD Dalek
Cybran T2 PD Anode
Cybran T2 Tank Hippo
Cybran T2 Bot Hoplite
Cybran T2 Ambush Bot Scorpion
