### ISSUE TITLE
Manually change build time on problematic units

### ISSUE THREAD

**Issue by Kami-Interface** [Team-QUIET/QUIET-Community-Edition#92]
Evenflow causes very long or short build times for experimental where the E-cost is significantly parting from the 1:10 ratio that most units follow.

Such units should be manually balanced in their blueprint to have a shorter or longer build time (without changing the cost of the unit)

Units so far identified:

- Megalith (increase build-time)
- StormStrider (reduce build-time)
- Mayhem (reduce build-time)

**Comment by fs-tom** [comment]
@Kami-Interface 


Could envision just enforcing the idealized 1:N ratio for mass/E (or push current values toward that ideal)?   This could be accomplished with a system-wide pass in blueprints.lua for instance.

**Comment by Kami-Interface** [comment]
Yeah changing the cost of the units is of course an option, I'm fine with that as well, (reducing energy cost to get build time down, maybe also bumping the mass cost to compensate if we think the unit is balanced otherwise)

**Comment by Azraeel** [comment]
Will probably change the Megalith & Monkeylord in the upcoming next patch @Kami-Interface

**Comment by Kami-Interface** [comment]
Monkeylord?

**Comment by Azraeel** [comment]
Monkeylord has 13k mass and same E cost as GC but its classed as heavy
for example GC cost like 50k mass or smth but monkey cost 13k mass?? 

But they are both 13m BT?

**Comment by Kami-Interface** [comment]
The Monkeylord is 17.5k mass, not 13k. I think the mass cost is pretty in line with the designation of medium if we go by the other experimental. I see what you mean though, it costs 17.5k mass and almost 500k energy. Do you want to rebalance it by bumping mass cost a bit while reducing the e-cost dramatically? If we manually adjust the build-time downwards while leaving costs unchanged it will be borderline rebuildable due to massive e-cost

**Comment by Azraeel** [comment]
Depends, its up to you.

**Comment by Azraeel** [comment]
In my opinion, i think we could rebalance the cost because it's far too Energy dependent also explains why Monkeylords trade so well.

**Comment by Kami-Interface** [comment]
If you slash the e-cost to something like 200k (which would be more in line with the 1:10), we will also get a much higher mass cost per tick, but I think that's fine, even with more than double the cost of what it currently is. Alternatively the e-cost could be reduced to 200k, mass bumped to 22k, and build-time set artificially to be as if the e-cost was, say, 300k. This way the mass cost per tick would still be higher, but not the 2.5x higher as if we used EvenFlow to calculate buildtime after slashing e cost

**Comment by Azraeel** [comment]
I think we try your first option and just be ok with a higher mass per tick.

**Comment by Kami-Interface** [comment]
I think a 5k mass increased cost could be warranted if we're reducing e-cost from almost 500k to say, 250k

**Comment by Azraeel** [comment]
its 17.5k at medium so it needs like maybe 7k or 8k mass increase imo because monkey is a highend medium experimental
