### ISSUE TITLE
Review torpedoes from submarines

### ISSUE THREAD

**Issue by rajderks** [Team-QUIET/QUIET-Community-Edition#93]
The t1 phase of naval warfare currently is a joke in my eyes
- T1 Submarines 2-shot each other and seem way too stronk (killing factory in a two salvo when you have 6/7 subs). There seems to be NO chance of regaining naval control if you lose the first battle.
- 4 T2 Aeon submarines killed a HARMS without taking any damage (and killed it at record pace!)

Suggestions:
- T1/2 sub damage cut, start with a 25% damage reduction and see where it goes

[LastGame.zip](https://github.com/user-attachments/files/17017633/LastGame.zip)

**Comment by Azraeel** [comment]
T2 was cut, in terms of t1 i will consider it if i see more games of them being OP. Current recommendation is T1 Torpedos (Surprisingly)
